language: perl
sudo: true

perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

install:
    - sudo apt-get install libchromaprint-dev
    - cpanm --notest Pod::Checker Test::MemoryGrowth

script:
    - make test
